import localFont from "next/font/local";

import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/redux-provider";
import { Toaster } from "sonner";

const montreal = localFont({
  src: [
    {
      path: "../public/fonts/PPNeueMontreal-Hairline.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontreal-HairlineItalic.otf",
      weight: "100",
      style: "italic",
    },

    {
      path: "../public/fonts/PPNeueMontreal-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontreal-LightItalic.otf",
      weight: "300",
      style: "italic",
    },

    {
      path: "../public/fonts/PPNeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontreal-Italic.otf",
      weight: "400",
      style: "italic",
    },

    {
      path: "../public/fonts/PPNeueMontrealText-Book.otf",
      weight: "375",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontrealText-BookItalic.otf",
      weight: "375",
      style: "italic",
    },

    {
      path: "../public/fonts/PPNeueMontreal-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontreal-SemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },

    {
      path: "../public/fonts/PPNeueMontreal-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/PPNeueMontreal-ExtraboldItalic.otf",
      weight: "800",
      style: "italic",
    },
  ],
  variable: "--font-montreal",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: {
    default: "Simplerp",
    template: "%s | Simplerp",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montreal.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          {children}
          <Toaster
            richColors
            position="top-center"
            offset={120}
            mobileOffset={100}
            className="fixed z-50 top"
            expand={true}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
